export enum NsbClassification {
  GOVERNMENT_AGENCY = 'GOVERNMENT_AGENCY',
  PARASTATAL = 'PARASTATAL',
  PRIVATE = 'PRIVATE',
  OTHER = 'OTHER',
}

export enum NsbStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
}

export enum StakeholderRegistryStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
}

export enum NsbContactType {
  PRIMARY = 'PRIMARY',
  ALTERNATIVE = 'ALTERNATIVE',
  TECHNICAL = 'TECHNICAL',
  FINANCIAL = 'FINANCIAL',
  ARSO_LIAISON = 'ARSO_LIAISON',
  ACAP_COORDINATOR = 'ACAP_COORDINATOR',
  MARKET_SURVEILLANCE_FOCAL_POINT = 'MARKET_SURVEILLANCE_FOCAL_POINT',
  CUSTOMS_TRADE_FOCAL_POINT = 'CUSTOMS_TRADE_FOCAL_POINT',
  CONSUMER_AFFAIRS_FOCAL_POINT = 'CONSUMER_AFFAIRS_FOCAL_POINT',
}

export enum NsbLocationType {
  HEADQUARTERS = 'HEADQUARTERS',
  BRANCH = 'BRANCH',
  LABORATORY = 'LABORATORY',
  REGIONAL_OFFICE = 'REGIONAL_OFFICE',
}

export enum ApplicationType {
  FULL = 'FULL',
  PROVISIONAL = 'PROVISIONAL',
  RENEWAL = 'RENEWAL',
  SCOPE_EXTENSION = 'SCOPE_EXTENSION',
}

export enum ApplicationStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  PENDING_WITNESS = 'PENDING_WITNESS',
  PENDING_CACO = 'PENDING_CACO',
  APPROVED_PENDING_PAYMENT = 'APPROVED_PENDING_PAYMENT',
  APPROVED_PENDING_AGREEMENT = 'APPROVED_PENDING_AGREEMENT',
  ACTIVE = 'ACTIVE',
  PROVISIONAL = 'PROVISIONAL',
  SUSPENDED = 'SUSPENDED',
  WITHDRAWN = 'WITHDRAWN',
  REJECTED = 'REJECTED',
}

export enum LicenseType {
  FULL = 'FULL',
  PROVISIONAL = 'PROVISIONAL',
}

export enum LicenseStatus {
  ACTIVE = 'ACTIVE',
  PROVISIONAL = 'PROVISIONAL',
  SUSPENDED = 'SUSPENDED',
  WITHDRAWN = 'WITHDRAWN',
  EXPIRED = 'EXPIRED',
  REVOKED = 'REVOKED',
}

export enum ComplianceType {
  SURVEILLANCE = 'SURVEILLANCE',
  RECERTIFICATION = 'RECERTIFICATION',
  WITNESS_AUDIT = 'WITNESS_AUDIT',
}

export enum ComplianceStatus {
  SCHEDULED = 'SCHEDULED',
  COMPLETED = 'COMPLETED',
  OVERDUE = 'OVERDUE',
  CANCELLED = 'CANCELLED',
}

export enum DocumentType {
  LEGAL_REGISTRATION = 'LEGAL_REGISTRATION',
  ACCREDITATION_CERTIFICATE = 'ACCREDITATION_CERTIFICATE',
  QUALITY_MANUAL = 'QUALITY_MANUAL',
  AUDITOR_COMPETENCE_MATRIX = 'AUDITOR_COMPETENCE_MATRIX',
  OTHER = 'OTHER',
}

export enum DocumentVerificationStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum MembershipStatus {
  MEMBER = 'MEMBER',
  CANDIDATE = 'CANDIDATE',
  SUSPENDED = 'SUSPENDED',
  WITHDRAWN = 'WITHDRAWN',
}

export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',           // ARSO Central Secretariat super admin
  ARSO_COUNCIL = 'ARSO_COUNCIL',        // ARSO Council member
  CACO_MEMBER = 'CACO_MEMBER',         // ARSO Conformity Assessment Committee member
  ARSO_SECRETARIAT = 'ARSO_SECRETARIAT', // ARSO Central Secretariat staff
  ADVISORY_COMMITTEE = 'ADVISORY_COMMITTEE', // Advisory Committee member
  SMC_MEMBER = 'SMC_MEMBER',           // Standards Management Committee member
  NSB_ADMIN = 'NSB_ADMIN',             // National Standards Body administrator
  NSB_USER = 'NSB_USER',               // National Standards Body user
  CB_ADMIN = 'CB_ADMIN',               // Certification Body administrator
  CB_USER = 'CB_USER',                 // Certification Body user
  OPERATOR = 'OPERATOR',               // Certified client/operator
  ACCREDITATION_BODY = 'ACCREDITATION_BODY', // Accreditation Body user
  PUBLIC = 'PUBLIC',                   // Public user (limited access)
}

export enum RoleRequestStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum NsbRegistrationRequestStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum NsbDocumentType {
  NSB_ESTABLISHMENT_CHARTER = 'NSB_ESTABLISHMENT_CHARTER',
  ARSO_MEMBERSHIP_CERTIFICATE = 'ARSO_MEMBERSHIP_CERTIFICATE',
  GOVERNMENT_GAZETTE_NOTICE = 'GOVERNMENT_GAZETTE_NOTICE',
  DECLARATION_OF_AUTHORITY = 'DECLARATION_OF_AUTHORITY',
  NATIONAL_STANDARDS_ACT = 'NATIONAL_STANDARDS_ACT',
  NATIONAL_CONFORMITY_ASSESSMENT_POLICY = 'NATIONAL_CONFORMITY_ASSESSMENT_POLICY',
  ORGANIZATIONAL_CHART = 'ORGANIZATIONAL_CHART',
  OTHER = 'OTHER',
}

export enum NsbProfileDocumentType {
  NATIONAL_STANDARDS_ACT_DOCUMENT = 'NATIONAL_STANDARDS_ACT_DOCUMENT',
  NATIONAL_CONFORMITY_ASSESSMENT_POLICY_DOCUMENT = 'NATIONAL_CONFORMITY_ASSESSMENT_POLICY_DOCUMENT',
  NATIONAL_QUALITY_POLICY_DOCUMENT = 'NATIONAL_QUALITY_POLICY_DOCUMENT',
  ORGANIZATIONAL_CHART_DOCUMENT = 'ORGANIZATIONAL_CHART_DOCUMENT',
  OTHER = 'OTHER',
}

// Stakeholder Registry Enums (Phase 2.1)
export enum MsaJurisdiction {
  NATIONAL = 'NATIONAL',
  REGIONAL = 'REGIONAL',
}

export enum MouStatus {
  SIGNED = 'SIGNED',
  PENDING = 'PENDING',
  NOT_SIGNED = 'NOT_SIGNED',
  N_A = 'N/A',
}

export enum SystemAccessLevel {
  READ_ONLY = 'READ_ONLY',
  FULL = 'FULL',
}

export enum RegulatoryAgencyType {
  FOOD_DRUG_AUTHORITY = 'FOOD_DRUG_AUTHORITY',
  AGRICULTURE_MINISTRY = 'AGRICULTURE_MINISTRY',
  HEALTH_MINISTRY = 'HEALTH_MINISTRY',
  ENVIRONMENT_AGENCY = 'ENVIRONMENT_AGENCY',
  INDUSTRY_TRADE_MINISTRY = 'INDUSTRY_TRADE_MINISTRY',
  OTHER = 'OTHER',
}

export enum AccreditationStatus {
  AFRAC_MRA = 'AFRAC_MRA',
  OTHER = 'OTHER',
  NONE = 'NONE',
}

// Mark License System Enums (Phase 3)
export enum MarkLicenseType {
  PROMOTIONAL_INSTITUTIONAL = 'PROMOTIONAL_INSTITUTIONAL',
  CERTIFICATION_BODY = 'CERTIFICATION_BODY',
  SPECIAL_PROJECT = 'SPECIAL_PROJECT',
}

export enum MarkLicenseStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  APPROVED_PENDING_AGREEMENT = 'APPROVED_PENDING_AGREEMENT',
  PENDING_NSB_SIGNATURE = 'PENDING_NSB_SIGNATURE',
  PENDING_ARSO_SIGNATURE = 'PENDING_ARSO_SIGNATURE',
  EXECUTED = 'EXECUTED',
  ACTIVE = 'ACTIVE',
  EXPIRED = 'EXPIRED',
  SUSPENDED = 'SUSPENDED',
  REJECTED = 'REJECTED',
  WITHDRAWN = 'WITHDRAWN',
  TERMINATED = 'TERMINATED',
}

export enum MarkMisuseStatus {
  OPEN = 'OPEN',
  UNDER_REVIEW = 'UNDER_REVIEW',
  RESOLVED = 'RESOLVED',
  DISMISSED = 'DISMISSED',
}

export enum MarkSanctionType {
  WARNING = 'WARNING',
  SUSPENSION = 'SUSPENSION',
  WITHDRAWAL = 'WITHDRAWAL',
}

export enum MarkSanctionStatus {
  ACTIVE = 'ACTIVE',
  LIFTED = 'LIFTED',
}

export enum MarkType {
  ARSO_QUALITY_MARK = 'ARSO_QUALITY_MARK',
  ECO_MARK_AFRICA = 'ECO_MARK_AFRICA',
  BOTH = 'BOTH',
}

export enum MediaType {
  DIGITAL_ONLINE = 'DIGITAL_ONLINE',
  PRINT = 'PRINT',
  BROADCAST = 'BROADCAST',
  OUTDOOR = 'OUTDOOR',
  EVENTS = 'EVENTS',
  SOCIAL_MEDIA = 'SOCIAL_MEDIA',
  OTHER = 'OTHER',
}

export enum AgreementStatus {
  DRAFT = 'DRAFT',
  PENDING_NSB = 'PENDING_NSB',
  PENDING_ARSO = 'PENDING_ARSO',
  EXECUTED = 'EXECUTED',
  ARCHIVED = 'ARCHIVED',
}

export enum CertificationAgreementType {
  CERTIFICATION_AGREEMENT = 'CERTIFICATION_AGREEMENT',
  SUB_LICENSE_AGREEMENT = 'SUB_LICENSE_AGREEMENT',
}

export enum CertificationAgreementStatus {
  PENDING_CB_APPROVAL = 'PENDING_CB_APPROVAL',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum CbChangeRequestStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum ReportStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  REQUIRES_REVISION = 'REQUIRES_REVISION',
}

export enum ComplaintStatus {
  RECEIVED = 'RECEIVED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  CLOSED = 'CLOSED',
  REJECTED = 'REJECTED',
}

export enum AppealStatus {
  RECEIVED = 'RECEIVED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  DECIDED = 'DECIDED',
  REJECTED = 'REJECTED',
}

export enum ModificationStatus {
  PENDING = 'PENDING',
  UNDER_REVIEW = 'UNDER_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  IMPLEMENTED = 'IMPLEMENTED',
}

export enum AssetDeliveryMethod {
  PORTAL_DOWNLOAD = 'PORTAL_DOWNLOAD',
  EMAIL_DELIVERY = 'EMAIL_DELIVERY',
  PHYSICAL_MEDIA = 'PHYSICAL_MEDIA',
  OTHER = 'OTHER',
}

export enum AssetFileType {
  VECTOR_AI = 'VECTOR_AI',
  VECTOR_EPS = 'VECTOR_EPS',
  PNG = 'PNG',
  JPEG = 'JPEG',
  PDF = 'PDF',
  VIDEO = 'VIDEO',
  OTHER = 'OTHER',
}

export enum LicenseDurationType {
  ONE_YEAR = 'ONE_YEAR',
  TWO_YEARS = 'TWO_YEARS',
  THREE_YEARS = 'THREE_YEARS',
  PROJECT_BASED = 'PROJECT_BASED',
  OTHER = 'OTHER',
}

// Operator Registration System Enums (OP-001)
export enum OperatorType {
  MANUFACTURER = 'MANUFACTURER',
  IMPORTER = 'IMPORTER',
  EXPORTER = 'EXPORTER',
  DISTRIBUTOR = 'DISTRIBUTOR',
  RETAILER = 'RETAILER',
  SERVICE_PROVIDER = 'SERVICE_PROVIDER',
  OTHER = 'OTHER',
}

export enum LegalStructure {
  LIMITED_COMPANY = 'LIMITED_COMPANY',
  PARTNERSHIP = 'PARTNERSHIP',
  SOLE_PROPRIETOR = 'SOLE_PROPRIETOR',
  NGO = 'NGO',
  GOVERNMENT = 'GOVERNMENT',
  COOPERATIVE = 'COOPERATIVE',
  OTHER = 'OTHER',
}

export enum EmployeeCountRange {
  MICRO_1_9 = 'MICRO_1_9',
  SMALL_10_49 = 'SMALL_10_49',
  MEDIUM_50_249 = 'MEDIUM_50_249',
  LARGE_250_PLUS = 'LARGE_250_PLUS',
}

export enum AnnualTurnoverRange {
  UNDER_50K = 'UNDER_50K',
  '50K_100K' = '50K_100K',
  '100K_500K' = '100K_500K',
  '500K_1M' = '500K_1M',
  '1M_5M' = '1M_5M',
  '5M_10M' = '5M_10M',
  OVER_10M = 'OVER_10M',
}

export enum OwnershipType {
  LOCAL = 'LOCAL',
  FOREIGN = 'FOREIGN',
  JOINT_VENTURE = 'JOINT_VENTURE',
  PUBLIC = 'PUBLIC',
  GOVERNMENT = 'GOVERNMENT',
  MIXED = 'MIXED',
}

export enum SMECategory {
  MICRO = 'MICRO',
  SMALL = 'SMALL',
  MEDIUM = 'MEDIUM',
  LARGE = 'LARGE',
  NOT_APPLICABLE = 'NOT_APPLICABLE',
}

export enum OwnershipStatus {
  YES = 'YES',
  NO = 'NO',
  WOMEN_LED = 'WOMEN_LED',
  YOUTH_LED = 'YOUTH_LED',
}

export enum LegalRegistrationNumberType {
  BUSINESS_REGISTRATION = 'BUSINESS_REGISTRATION',
  TAX_ID = 'TAX_ID',
  VAT = 'VAT',
  OTHER = 'OTHER',
}

export enum OperatorStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  SUSPENDED = 'SUSPENDED',
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}

export enum ApplicationRegistrationStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  WITHDRAWN = 'WITHDRAWN',
}

export enum CbApplicationStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  APPROVED = 'APPROVED',
  PROVISIONAL = 'PROVISIONAL',
  SUSPENDED = 'SUSPENDED',
  WITHDRAWN = 'WITHDRAWN',
  REJECTED = 'REJECTED',
}

export enum CbAccreditationStandard {
  ISO_IEC_17065 = 'ISO_IEC_17065',
  ISO_IEC_17021_1 = 'ISO_IEC_17021_1',
  OTHER = 'OTHER',
}

export enum CbDocumentType {
  LEGAL_REGISTRATION = 'LEGAL_REGISTRATION',
  ACCREDITATION_CERTIFICATE = 'ACCREDITATION_CERTIFICATE',
  ACCREDITATION_SCOPE = 'ACCREDITATION_SCOPE',
  ACKNOWLEDGEMENT_OF_APPLICATION = 'ACKNOWLEDGEMENT_OF_APPLICATION',
  OTHER = 'OTHER',
}

export enum OperatorContactType {
  PRIMARY = 'PRIMARY',
  ALTERNATIVE = 'ALTERNATIVE',
  TECHNICAL = 'TECHNICAL',
  FINANCIAL = 'FINANCIAL',
  LEGAL = 'LEGAL',
}

export enum VerificationStatus {
  PENDING = 'PENDING',
  VERIFIED = 'VERIFIED',
  FAILED = 'FAILED',
  EXPIRED = 'EXPIRED',
}

export enum OperatorLocationType {
  REGISTERED_ADDRESS = 'REGISTERED_ADDRESS',
  FACTORY = 'FACTORY',
  PRODUCTION_FACILITY = 'PRODUCTION_FACILITY',
  WAREHOUSE = 'WAREHOUSE',
  OFFICE = 'OFFICE',
  OTHER = 'OTHER',
}

export enum FactoryType {
  MANUFACTURING_PLANT = 'MANUFACTURING_PLANT',
  PROCESSING_UNIT = 'PROCESSING_UNIT',
  ASSEMBLY_LINE = 'ASSEMBLY_LINE',
  WORKSHOP = 'WORKSHOP',
  PACKAGING_FACILITY = 'PACKAGING_FACILITY',
  OTHER = 'OTHER',
}

export enum MainBusinessSector {
  AGRICULTURE = 'AGRICULTURE',
  MANUFACTURING = 'MANUFACTURING',
  SERVICES = 'SERVICES',
  CONSTRUCTION = 'CONSTRUCTION',
  MINING = 'MINING',
  RETAIL = 'RETAIL',
  WHOLESALE = 'WHOLESALE',
  TRANSPORT = 'TRANSPORT',
  ENERGY = 'ENERGY',
  TELECOMMUNICATIONS = 'TELECOMMUNICATIONS',
  OTHER = 'OTHER',
}

export enum DomesticMarketType {
  NATIONAL = 'NATIONAL',
  REGIONAL = 'REGIONAL',
  LOCAL = 'LOCAL',
}

export enum QMSType {
  ISO_9001 = 'ISO_9001',
  HACCP = 'HACCP',
  GMP = 'GMP',
  INTERNAL_SYSTEM = 'INTERNAL_SYSTEM',
  NONE = 'NONE',
  IN_PROGRESS = 'IN_PROGRESS',
}

export enum PreferredLanguage {
  ENGLISH = 'ENGLISH',
  FRENCH = 'FRENCH',
  PORTUGUESE = 'PORTUGUESE',
  ARABIC = 'ARABIC',
  SWAHILI = 'SWAHILI',
  OTHER = 'OTHER',
}

export enum CommunicationPreference {
  EMAIL = 'EMAIL',
  SMS = 'SMS',
  PHONE = 'PHONE',
  WHATSAPP = 'WHATSAPP',
  POSTAL_MAIL = 'POSTAL_MAIL',
  IN_PERSON = 'IN_PERSON',
}

export enum NotificationFrequency {
  REAL_TIME = 'REAL_TIME',
  DAILY_DIGEST = 'DAILY_DIGEST',
  WEEKLY_SUMMARY = 'WEEKLY_SUMMARY',
  MONTHLY_SUMMARY = 'MONTHLY_SUMMARY',
}

export enum DigitalLiteracyLevel {
  BASIC = 'BASIC',
  INTERMEDIATE = 'INTERMEDIATE',
  ADVANCED = 'ADVANCED',
}

export enum InternetAccessType {
  HIGH_SPEED = 'HIGH_SPEED',
  MOBILE_DATA = 'MOBILE_DATA',
  LIMITED = 'LIMITED',
  INTERMITTENT = 'INTERMITTENT',
}

export enum DeviceType {
  DESKTOP = 'DESKTOP',
  LAPTOP = 'LAPTOP',
  SMARTPHONE = 'SMARTPHONE',
  TABLET = 'TABLET',
  FEATURE_PHONE = 'FEATURE_PHONE',
}

export enum AssistiveTechType {
  SCREEN_READER = 'SCREEN_READER',
  HIGH_CONTRAST = 'HIGH_CONTRAST',
  LARGE_TEXT = 'LARGE_TEXT',
  TEXT_TO_SPEECH = 'TEXT_TO_SPEECH',
  KEYBOARD_NAVIGATION = 'KEYBOARD_NAVIGATION',
  OTHER = 'OTHER',
}

// Product Certification System Enums (OP-002)
export enum CertificationSchemeType {
  SCHEME_1_TYPE_TESTING = 'SCHEME_1_TYPE_TESTING',
  SCHEME_2_TESTING_SURVEILLANCE = 'SCHEME_2_TESTING_SURVEILLANCE',
  SCHEME_3_TESTING_QUALITY_SYSTEM = 'SCHEME_3_TESTING_QUALITY_SYSTEM',
  SCHEME_4_BATCH_TESTING = 'SCHEME_4_BATCH_TESTING',
  SCHEME_5_100_PERCENT_TESTING = 'SCHEME_5_100_PERCENT_TESTING',
}

export enum ApplicationScope {
  SINGLE_PRODUCT = 'SINGLE_PRODUCT',
  PRODUCT_FAMILY = 'PRODUCT_FAMILY',
  MULTIPLE_PRODUCTS = 'MULTIPLE_PRODUCTS',
  FACTORY_PROCESS = 'FACTORY_PROCESS',
  MULTIPLE_FACTORIES = 'MULTIPLE_FACTORIES',
}

export enum ProductCertificationType {
  NEW_CERTIFICATION = 'NEW_CERTIFICATION',
  RENEWAL = 'RENEWAL',
  EXTENSION_NEW_PRODUCTS = 'EXTENSION_NEW_PRODUCTS',
  TRANSFER_FROM_OTHER_CB = 'TRANSFER_FROM_OTHER_CB',
  SCOPE_EXTENSION = 'SCOPE_EXTENSION',
}

export enum ProductCertificationStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  PENDING_DOCUMENTS = 'PENDING_DOCUMENTS',
  PENDING_TESTING = 'PENDING_TESTING',
  PENDING_AUDIT = 'PENDING_AUDIT',
  APPROVED_PENDING_PAYMENT = 'APPROVED_PENDING_PAYMENT',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  WITHDRAWN = 'WITHDRAWN',
  SUSPENDED = 'SUSPENDED',
  CERTIFIED = 'CERTIFIED',
  EXPIRED = 'EXPIRED',
}

export enum MarkRequestedType {
  ARSO_QUALITY_MARK = 'ARSO_QUALITY_MARK',
  ECO_MARK_AFRICA = 'ECO_MARK_AFRICA',
  BOTH = 'BOTH',
}

export enum MarkCombinationPreference {
  BOTH_MARKS_SAME_PRODUCT = 'BOTH_MARKS_SAME_PRODUCT',
  SEPARATE_MARKS_DIFFERENT_PRODUCTS = 'SEPARATE_MARKS_DIFFERENT_PRODUCTS',
  UNDECIDED = 'UNDECIDED',
}

export enum PriorityProcessing {
  YES = 'YES',
  NO = 'NO',
}

export enum ExpectedTimeline {
  URGENT_1_2_MONTHS = 'URGENT_1_2_MONTHS',
  STANDARD_3_4_MONTHS = 'STANDARD_3_4_MONTHS',
  FLEXIBLE_5_6_MONTHS = 'FLEXIBLE_5_6_MONTHS',
}

export enum ProductCategory {
  FOOD_BEVERAGE = 'FOOD_BEVERAGE',
  TEXTILES = 'TEXTILES',
  ELECTRONICS = 'ELECTRONICS',
  CHEMICALS = 'CHEMICALS',
  CONSTRUCTION = 'CONSTRUCTION',
  MACHINERY = 'MACHINERY',
  AGRICULTURE = 'AGRICULTURE',
  COSMETICS = 'COSMETICS',
  PHARMACEUTICALS = 'PHARMACEUTICALS',
  AUTOMOTIVE = 'AUTOMOTIVE',
  OTHER = 'OTHER',
}

export enum TargetConsumerGroup {
  GENERAL_PUBLIC = 'GENERAL_PUBLIC',
  CHILDREN = 'CHILDREN',
  ELDERLY = 'ELDERLY',
  PREGNANT_WOMEN = 'PREGNANT_WOMEN',
  PROFESSIONALS = 'PROFESSIONALS',
  INDUSTRIAL_USERS = 'INDUSTRIAL_USERS',
  INSTITUTIONAL = 'INSTITUTIONAL',
  OTHER = 'OTHER',
}

export enum PackagingType {
  BOTTLE = 'BOTTLE',
  BOX = 'BOX',
  POUCH = 'POUCH',
  BAG = 'BAG',
  CAN = 'CAN',
  JAR = 'JAR',
  BULK = 'BULK',
  OTHER = 'OTHER',
}

export enum StandardComplianceStatus {
  FULLY_COMPLIANT = 'FULLY_COMPLIANT',
  PARTIALLY_COMPLIANT = 'PARTIALLY_COMPLIANT',
  NON_COMPLIANT = 'NON_COMPLIANT',
  UNKNOWN = 'UNKNOWN',
}

export enum TechnicalDocsStatus {
  COMPLETE = 'COMPLETE',
  PARTIAL = 'PARTIAL',
  NONE = 'NONE',
}

export enum TestReportsAvailability {
  YES_ACCREDITED_LAB = 'YES_ACCREDITED_LAB',
  YES_NON_ACCREDITED = 'YES_NON_ACCREDITED',
  SOME = 'SOME',
  NONE = 'NONE',
}

export enum TraceabilityStatus {
  FULL = 'FULL',
  PARTIAL = 'PARTIAL',
  NONE = 'NONE',
}

export enum EnvironmentalBenefit {
  ENERGY_EFFICIENT = 'ENERGY_EFFICIENT',
  WATER_EFFICIENT = 'WATER_EFFICIENT',
  RECYCLABLE = 'RECYCLABLE',
  BIODEGRADABLE = 'BIODEGRADABLE',
  COMPOSTABLE = 'COMPOSTABLE',
  LOW_EMISSIONS = 'LOW_EMISSIONS',
  REDUCED_WASTE = 'REDUCED_WASTE',
  SUSTAINABLE_SOURCING = 'SUSTAINABLE_SOURCING',
  RENEWABLE_MATERIALS = 'RENEWABLE_MATERIALS',
  CARBON_NEUTRAL = 'CARBON_NEUTRAL',
  OTHER = 'OTHER',
}

export enum ThirdPartyVerificationStatus {
  YES = 'YES',
  NO = 'NO',
  IN_PROGRESS = 'IN_PROGRESS',
}

export enum LifecycleAssessmentType {
  FULL_LCA = 'FULL_LCA',
  PARTIAL_LCA = 'PARTIAL_LCA',
  SCREENING_LCA = 'SCREENING_LCA',
  NONE = 'NONE',
}

export enum LifecycleAspect {
  RAW_MATERIAL_EXTRACTION = 'RAW_MATERIAL_EXTRACTION',
  MATERIAL_PROCESSING = 'MATERIAL_PROCESSING',
  MANUFACTURING = 'MANUFACTURING',
  PACKAGING = 'PACKAGING',
  DISTRIBUTION = 'DISTRIBUTION',
  USE_CONSUMPTION = 'USE_CONSUMPTION',
  END_OF_LIFE_DISPOSAL = 'END_OF_LIFE_DISPOSAL',
  RECYCLING = 'RECYCLING',
}

export enum EnvironmentalManagementSystem {
  ISO_14001_CERTIFIED = 'ISO_14001_CERTIFIED',
  INTERNAL_EMS = 'INTERNAL_EMS',
  NONE = 'NONE',
}

export enum TakeBackProgramStatus {
  YES = 'YES',
  NO = 'NO',
  PLANNED = 'PLANNED',
}

export enum AuditLanguage {
  ENGLISH = 'ENGLISH',
  FRENCH = 'FRENCH',
  PORTUGUESE = 'PORTUGUESE',
  ARABIC = 'ARABIC',
  LOCAL_LANGUAGE = 'LOCAL_LANGUAGE',
}

export enum AuditTeamSize {
  ONE_AUDITOR = 'ONE_AUDITOR',
  TWO_AUDITORS = 'TWO_AUDITORS',
  FLEXIBLE = 'FLEXIBLE',
}

export enum CertificationAuditType {
  DOCUMENT_REVIEW = 'DOCUMENT_REVIEW',
  INITIAL = 'INITIAL',
  SURVEILLANCE = 'SURVEILLANCE',
  RECERTIFICATION = 'RECERTIFICATION',
  FOLLOW_UP = 'FOLLOW_UP',
  UNANNOUNCED = 'UNANNOUNCED',
}

export enum AuditFindingType {
  MAJOR = 'MAJOR',
  MINOR = 'MINOR',
  OBSERVATION = 'OBSERVATION',
  CRITICAL = 'CRITICAL',
}

export enum AuditFindingStatus {
  OPEN = 'OPEN',
  UNDER_REVIEW = 'UNDER_REVIEW',
  CLOSED = 'CLOSED',
}

export enum CorrectiveActionStatus {
  PENDING = 'PENDING',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
}

export enum SamplingStatus {
  PENDING = 'PENDING',
  COLLECTED = 'COLLECTED',
  TESTED = 'TESTED',
}

export enum TestResultStatus {
  PASS = 'PASS',
  FAIL = 'FAIL',
  CONDITIONAL_PASS = 'CONDITIONAL_PASS',
}

export enum VolumeUnit {
  UNITS = 'UNITS',
  KG = 'KG',
  LITERS = 'LITERS',
  TONNES = 'TONNES',
  CONTAINERS = 'CONTAINERS',
  PALLETS = 'PALLETS',
  CUBIC_METERS = 'CUBIC_METERS',
  OTHER = 'OTHER',
}

// Document Upload System Enums (OP-003)
export enum DocumentCategory {
  COMPANY_LEGAL = 'COMPANY_LEGAL',
  QUALITY_MANAGEMENT = 'QUALITY_MANAGEMENT',
  TECHNICAL_PRODUCTION = 'TECHNICAL_PRODUCTION',
  TEST_REPORTS = 'TEST_REPORTS',
  CERTIFICATES = 'CERTIFICATES',
  SUPPLY_CHAIN = 'SUPPLY_CHAIN',
  ENVIRONMENTAL = 'ENVIRONMENTAL',
  OTHER = 'OTHER',
}

export enum OperatorDocumentType {
  BUSINESS_REGISTRATION = 'BUSINESS_REGISTRATION',
  TAX_CERTIFICATE = 'TAX_CERTIFICATE',
  MEMORANDUM_ARTICLES = 'MEMORANDUM_ARTICLES',
  DIRECTORS_LIST = 'DIRECTORS_LIST',
  OWNERSHIP_STRUCTURE = 'OWNERSHIP_STRUCTURE',
  AUTHORIZED_SIGNATORY = 'AUTHORIZED_SIGNATORY',
  QUALITY_MANUAL = 'QUALITY_MANUAL',
  PROCEDURES_MANUAL = 'PROCEDURES_MANUAL',
  ORGANIZATIONAL_CHART = 'ORGANIZATIONAL_CHART',
  JOB_DESCRIPTIONS = 'JOB_DESCRIPTIONS',
  TRAINING_RECORDS = 'TRAINING_RECORDS',
  INTERNAL_AUDIT_RECORDS = 'INTERNAL_AUDIT_RECORDS',
  MANAGEMENT_REVIEW = 'MANAGEMENT_REVIEW',
  FACTORY_LAYOUT = 'FACTORY_LAYOUT',
  EQUIPMENT_LIST = 'EQUIPMENT_LIST',
  CALIBRATION_CERTIFICATES = 'CALIBRATION_CERTIFICATES',
  MAINTENANCE_RECORDS = 'MAINTENANCE_RECORDS',
  PROCESS_FLOW_DIAGRAMS = 'PROCESS_FLOW_DIAGRAMS',
  CONTROL_PLANS = 'CONTROL_PLANS',
  RAW_MATERIAL_SPECS = 'RAW_MATERIAL_SPECS',
  FINISHED_PRODUCT_SPECS = 'FINISHED_PRODUCT_SPECS',
  TEST_REPORT = 'TEST_REPORT',
  EXISTING_CERTIFICATE = 'EXISTING_CERTIFICATE',
  SUPPLIER_LIST = 'SUPPLIER_LIST',
  SUPPLIER_EVALUATION = 'SUPPLIER_EVALUATION',
  MATERIAL_CERTIFICATE = 'MATERIAL_CERTIFICATE',
  TRACEABILITY_RECORDS = 'TRACEABILITY_RECORDS',
  BATCH_RECORDS = 'BATCH_RECORDS',
  RECALL_PROCEDURE = 'RECALL_PROCEDURE',
  ENVIRONMENTAL_POLICY = 'ENVIRONMENTAL_POLICY',
  ENVIRONMENTAL_MANUAL = 'ENVIRONMENTAL_MANUAL',
  LCA_REPORT = 'LCA_REPORT',
  CARBON_FOOTPRINT_REPORT = 'CARBON_FOOTPRINT_REPORT',
  ENERGY_AUDIT = 'ENERGY_AUDIT',
  WASTE_AUDIT = 'WASTE_AUDIT',
  RECYCLING_CERTIFICATE = 'RECYCLING_CERTIFICATE',
  SUSTAINABLE_SOURCING = 'SUSTAINABLE_SOURCING',
  OTHER = 'OTHER',
}

export enum DocumentVerificationStatusExtended {
  PENDING = 'PENDING',
  UNDER_REVIEW = 'UNDER_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
  REQUIRES_REVISION = 'REQUIRES_REVISION',
}

export enum TestReportStatus {
  PENDING = 'PENDING',
  VERIFIED = 'VERIFIED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum PassFailStatus {
  PASS = 'PASS',
  FAIL = 'FAIL',
  CONDITIONAL_PASS = 'CONDITIONAL_PASS',
}

export enum FileFormat {
  PDF = 'PDF',
  JPG = 'JPG',
  PNG = 'PNG',
  DOC = 'DOC',
  DOCX = 'DOCX',
  XLS = 'XLS',
  XLSX = 'XLSX',
  CSV = 'CSV',
  DWG = 'DWG',
  AI = 'AI',
  EPS = 'EPS',
  OTHER = 'OTHER',
}

