export enum NsbClassification {
  GOVERNMENT_AGENCY = 'GOVERNMENT_AGENCY',
  PARASTATAL = 'PARASTATAL',
  PRIVATE = 'PRIVATE',
  OTHER = 'OTHER',
}

export enum NsbStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
}

export enum NsbContactType {
  PRIMARY = 'PRIMARY',
  ALTERNATIVE = 'ALTERNATIVE',
  TECHNICAL = 'TECHNICAL',
  FINANCIAL = 'FINANCIAL',
  ARSO_LIAISON = 'ARSO_LIAISON',
  ACAP_COORDINATOR = 'ACAP_COORDINATOR',
  MARKET_SURVEILLANCE_FOCAL_POINT = 'MARKET_SURVEILLANCE_FOCAL_POINT',
  CUSTOMS_TRADE_FOCAL_POINT = 'CUSTOMS_TRADE_FOCAL_POINT',
  CONSUMER_AFFAIRS_FOCAL_POINT = 'CONSUMER_AFFAIRS_FOCAL_POINT',
}

export enum NsbLocationType {
  HEADQUARTERS = 'HEADQUARTERS',
  BRANCH = 'BRANCH',
  LABORATORY = 'LABORATORY',
  REGIONAL_OFFICE = 'REGIONAL_OFFICE',
}

export enum ApplicationType {
  FULL = 'FULL',
  PROVISIONAL = 'PROVISIONAL',
  RENEWAL = 'RENEWAL',
  SCOPE_EXTENSION = 'SCOPE_EXTENSION',
}

export enum ApplicationStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  PENDING_WITNESS = 'PENDING_WITNESS',
  PENDING_CACO = 'PENDING_CACO',
  APPROVED_PENDING_PAYMENT = 'APPROVED_PENDING_PAYMENT',
  APPROVED_PENDING_AGREEMENT = 'APPROVED_PENDING_AGREEMENT',
  ACTIVE = 'ACTIVE',
  PROVISIONAL = 'PROVISIONAL',
  SUSPENDED = 'SUSPENDED',
  WITHDRAWN = 'WITHDRAWN',
  REJECTED = 'REJECTED',
}

export enum LicenseType {
  FULL = 'FULL',
  PROVISIONAL = 'PROVISIONAL',
}

export enum LicenseStatus {
  ACTIVE = 'ACTIVE',
  PROVISIONAL = 'PROVISIONAL',
  SUSPENDED = 'SUSPENDED',
  WITHDRAWN = 'WITHDRAWN',
  EXPIRED = 'EXPIRED',
  REVOKED = 'REVOKED',
}

export enum ComplianceType {
  SURVEILLANCE = 'SURVEILLANCE',
  RECERTIFICATION = 'RECERTIFICATION',
  WITNESS_AUDIT = 'WITNESS_AUDIT',
}

export enum ComplianceStatus {
  SCHEDULED = 'SCHEDULED',
  COMPLETED = 'COMPLETED',
  OVERDUE = 'OVERDUE',
  CANCELLED = 'CANCELLED',
}

export enum DocumentType {
  LEGAL_REGISTRATION = 'LEGAL_REGISTRATION',
  ACCREDITATION_CERTIFICATE = 'ACCREDITATION_CERTIFICATE',
  QUALITY_MANUAL = 'QUALITY_MANUAL',
  AUDITOR_COMPETENCE_MATRIX = 'AUDITOR_COMPETENCE_MATRIX',
  OTHER = 'OTHER',
}

export enum DocumentVerificationStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum MembershipStatus {
  MEMBER = 'MEMBER',
  CANDIDATE = 'CANDIDATE',
  SUSPENDED = 'SUSPENDED',
  WITHDRAWN = 'WITHDRAWN',
}

export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',           // ARSO Central Secretariat super admin
  ARSO_COUNCIL = 'ARSO_COUNCIL',        // ARSO Council member
  CACO_MEMBER = 'CACO_MEMBER',         // ARSO Conformity Assessment Committee member
  ARSO_SECRETARIAT = 'ARSO_SECRETARIAT', // ARSO Central Secretariat staff
  ADVISORY_COMMITTEE = 'ADVISORY_COMMITTEE', // Advisory Committee member
  SMC_MEMBER = 'SMC_MEMBER',           // Standards Management Committee member
  NSB_ADMIN = 'NSB_ADMIN',             // National Standards Body administrator
  NSB_USER = 'NSB_USER',               // National Standards Body user
  CB_ADMIN = 'CB_ADMIN',               // Certification Body administrator
  CB_USER = 'CB_USER',                 // Certification Body user
  OPERATOR = 'OPERATOR',               // Certified client/operator
  ACCREDITATION_BODY = 'ACCREDITATION_BODY', // Accreditation Body user
  PUBLIC = 'PUBLIC',                   // Public user (limited access)
}

export enum RoleRequestStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum NsbRegistrationRequestStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum NsbDocumentType {
  NSB_ESTABLISHMENT_CHARTER = 'NSB_ESTABLISHMENT_CHARTER',
  ARSO_MEMBERSHIP_CERTIFICATE = 'ARSO_MEMBERSHIP_CERTIFICATE',
  GOVERNMENT_GAZETTE_NOTICE = 'GOVERNMENT_GAZETTE_NOTICE',
  DECLARATION_OF_AUTHORITY = 'DECLARATION_OF_AUTHORITY',
  NATIONAL_STANDARDS_ACT = 'NATIONAL_STANDARDS_ACT',
  NATIONAL_CONFORMITY_ASSESSMENT_POLICY = 'NATIONAL_CONFORMITY_ASSESSMENT_POLICY',
  ORGANIZATIONAL_CHART = 'ORGANIZATIONAL_CHART',
  OTHER = 'OTHER',
}

export enum NsbProfileDocumentType {
  NATIONAL_STANDARDS_ACT_DOCUMENT = 'NATIONAL_STANDARDS_ACT_DOCUMENT',
  NATIONAL_CONFORMITY_ASSESSMENT_POLICY_DOCUMENT = 'NATIONAL_CONFORMITY_ASSESSMENT_POLICY_DOCUMENT',
  NATIONAL_QUALITY_POLICY_DOCUMENT = 'NATIONAL_QUALITY_POLICY_DOCUMENT',
  ORGANIZATIONAL_CHART_DOCUMENT = 'ORGANIZATIONAL_CHART_DOCUMENT',
  OTHER = 'OTHER',
}

// Stakeholder Registry Enums (Phase 2.1)
export enum MsaJurisdiction {
  NATIONAL = 'NATIONAL',
  REGIONAL = 'REGIONAL',
}

export enum MouStatus {
  SIGNED = 'SIGNED',
  PENDING = 'PENDING',
  NOT_SIGNED = 'NOT_SIGNED',
  N_A = 'N/A',
}

export enum SystemAccessLevel {
  READ_ONLY = 'READ_ONLY',
  FULL = 'FULL',
}

export enum RegulatoryAgencyType {
  FOOD_DRUG_AUTHORITY = 'FOOD_DRUG_AUTHORITY',
  AGRICULTURE_MINISTRY = 'AGRICULTURE_MINISTRY',
  HEALTH_MINISTRY = 'HEALTH_MINISTRY',
  ENVIRONMENT_AGENCY = 'ENVIRONMENT_AGENCY',
  INDUSTRY_TRADE_MINISTRY = 'INDUSTRY_TRADE_MINISTRY',
  OTHER = 'OTHER',
}

export enum AccreditationStatus {
  AFRAC_MRA = 'AFRAC_MRA',
  OTHER = 'OTHER',
  NONE = 'NONE',
}

